
**What is Data Preprocessing?**

Data preprocessing is an essential step in machine learning that involves transforming raw data into a clean and structured format suitable for modeling. It ensures that the data is accurate, complete, and ready for analysis, improving the performance and reliability of machine learning models.



**Steps in Data Preprocessing**

- **Importing Libraries**: Load necessary Python libraries like NumPy, Pandas, and Matplotlib.  
- **Loading the Dataset**: Read the dataset into a Pandas DataFrame.  
- **Handling Missing Values**: Impute missing values using mean, median, mode, or remove them if necessary.  
- **Encoding Categorical Data**: Convert categorical variables into numerical format using label encoding or one-hot encoding.  
- **Splitting Data into Training and Test Sets**: Divide the dataset into training and test sets to evaluate model performance.  
- **Feature Scaling**: Normalize or standardize features to bring them to the same scale.  






*Importing Required Libraries*

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

*Read the dataset into a Pandas DataFrame*

In [40]:
data = pd.read_csv("/content/Data.csv")
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [41]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [42]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [43]:
x[:,1:3] = np.round(x[:,1:3].astype(float),round(2))

*Handling Missing Values: Impute missing values using mean, median, mode, or remove them if necessary.*

In [44]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy = 'mean')
x[:,1:3] = imputer.fit_transform(x[:,1:3])

In [45]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


*Encoding Categorical Data: Convert categorical variables into numerical format using label encoding or one-hot encoding.*

In [46]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[0])],remainder = 'passthrough')
x = ct.fit_transform(x)

In [47]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [48]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [49]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


*Splitting Data into Training and Test Sets: Divide the dataset into training and test sets to evaluate model performance.*


In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=1)

In [51]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [52]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [53]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [54]:
print(y_test)

[0 1]


*Feature Scaling: Normalize or standardize features to bring them to the same scale.*

In [55]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [56]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [57]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
